name: "Rani"
description: "filters filters"
branding:
  icon: 'activity'
  color: 'green'

inputs:
  Destination_NAME:
    description: "destination's name of repo"
    required: true
  Destination_UNAME:
    description: "Idk"
    required: true
  Destination_REPO:
    description: "repo name"
    required: true
  Destination_VERSION:
    description: "version"
    required: true
  GIT_NAME:
    description: 'username'
    required: true
  GIT_EMAIL:
    description: 'email'
    required: true
  REPO_BRANCH:
    description: 'branch'
    required: true
    
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.Destination_NAME }}
    - ${{ inputs.Destination_UNAME }}
    - ${{ inputs.Destination_REPO }}
    - ${{ inputs.Destination_VERSION }}
    - ${{ inputs.GIT_NAME }}
    - ${{ inputs.GIT_EMAIL }}
    - ${{ inputs.REPO_BRANCH }}
