name: "Rani"
description: "filters filters"
branding:
  icon: 'activity'
  color: 'green'

inputs:
  Destination_NAME:
    description: "destination's name of repo"
    required: true
  Destination_UNAME:
    description: "Destination GitHub Username"
    required: true
  Destination_REPO:
    description: "Destination GitHub Repo Name"
    required: true
  Destination_FOLDER:
    description: "folder of action"
    required: true
  Destination_VERSION:
    description: "Version on Destination etc. Pro , ucate , Hell"
    required: true
  ACTION_FILE:
    description: 'action script for example look at action.example.py I'm calling this the Really Action Script'
    required: true
  GIT_NAME:
    description: 'Git Username'
    required: true
  GIT_EMAIL:
    description: 'Git E-mail'
    required: true
  REPO_BRANCH:
    description: 'Git Branch'
    required: true
    
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.Destination_NAME }}
    - ${{ inputs.Destination_UNAME }}
    - ${{ inputs.Destination_REPO }}
    - ${{ inputs.Destination_FOLDER }}
    - ${{ inputs.Destination_VERSION }}
    - ${{ inputs.ACTION_FILE }}
    - ${{ inputs.GIT_NAME }}
    - ${{ inputs.GIT_EMAIL }}
    - ${{ inputs.REPO_BRANCH }}
